version: 2

updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(app)"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - "ci"
    commit-message:
      prefix: "ci(app)"
